[worker]
<INSERT HERE IP ADDRESS>

[cp]
<INSERT HERE IP ADDRESS>

[worker:vars]
ansible_user=centos
ansible_ssh_private_key_file=~/.ssh/id_ed25519

[cp:vars]
ansible_user=centos
ansible_ssh_private_key_file=~/.ssh/id_ed25519
