# Placeholder for base values

###################################
##
## Test on a single replica
## Connectivity with questDB
##
###################################
#replicaCount: 1
#
#env:
#  # "dbname=qdb user=${QDB_PG_USER} password=${QDB_PG_PASSWORD} host=questdb_alerts port=8812"
#  # service_name.namespace.svc.cluster:service-port
#  PSYCOPG_QDB_CONN_STR: "dbname=qdb user=admin password=password host=questdb.questdb.svc.cluster.local port=8812"
#  # "dbname=postgres user=postgres password=${POSTGRES_PASSWORD} host=postgres port=5432"
#  PSYCOPG_KEY_CONN_STR: "dbname=postgres user=postgres password=postgres host=postgresql.postgresql.svc.cluster.local port=5432"
#  ADMIN_TOKEN: "ADMIN_TOKEN"
#  # "http::addr=questdb_alerts:9000;username=${QDB_PG_USER};password=${QDB_PG_PASSWORD};"
#  QDB_CLIENT_CONF: "http::addr=questdb.questdb.svc.cluster.local:9000;username=admin;password=password;"

###################################
##
## Test on a single replica, HPA
## Connectivity with Coco
##
###################################
#replicaCount: 1
#env:
#  # "dbname=qdb user=${QDB_PG_USER} password=${QDB_PG_PASSWORD} host=questdb_alerts port=8812"
#  # service_name.namespace.svc.cluster:service-port
#  PSYCOPG_QDB_CONN_STR: "dbname=qdb user=admin password=password host=questdb.questdb.svc.cluster.local port=8812"
#  # "dbname=postgres user=postgres password=${POSTGRES_PASSWORD} host=postgres port=5432"
#  PSYCOPG_KEY_CONN_STR: "dbname=postgres user=postgres password=postgres host=postgresql.postgresql.svc.cluster.local port=5432"
#  ADMIN_TOKEN: "ADMIN_TOKEN"
#  # "http::addr=questdb_alerts:9000;username=${QDB_PG_USER};password=${QDB_PG_PASSWORD};"
#  QDB_CLIENT_CONF: "http::areverse-proxy-local.reverse-proxy.svc.cluster.local:80;username=admin;password=password;"


###################################
##
## Test on rolling out
##
###################################

#replicaCount: 1
#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80


###################################
##
## Test on HA
##
###################################

replicaCount: 3
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80