

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
{{/*      tolerations:*/}}
{{/*        - key: node-role.kubernetes.io/control-plane*/}}
{{/*          operator: Exists*/}}
{{/*          effect: NoSchedule*/}}
      containers:
        - name: proxy
          image: ghcr.io/juangqcadavid/thesis_reverse_proxy:sha-e2a9702
          command:
            - "/bin/main"
          args:
            - "listen"
            - "-c"
            - "/config/config.yaml"
          volumeMounts:
            - name: config
              mountPath: /config
      priorityClassName: system-node-critical
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}-config
